- name: Create Tomorrow's TIL file
        run: |
          DATE=$(date -u -d "+9 hours +1 day" +'%Y-%m-%d')
          YEAR_MONTH=$(echo $DATE | cut -c 1-7)
          FILE_PATH="$YEAR_MONTH/$DATE.md"

          mkdir -p "$YEAR_MONTH"
          if [ ! -f "$FILE_PATH" ]; then
            cat << EOF > "$FILE_PATH"
## $DATE TIL

### 今日やったこと
- [ ]

### 今日学んだこと
-

### 気付き
>

### 次にやること
- [ ]
EOF
            git add "$FILE_PATH"
            git commit -m "Add TIL template for $DATE"
            git push
          fi